### Login User
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "warre",
  "password": "password123"
}

> {%
    client.global.set("auth_token", response.body);
%}

### Create Auction
POST http://localhost:8080/api/auctions
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "Vintage Wall Clock",
  "description": "A beautiful vintage clock from the 1950s.",
  "endTime": "2026-12-31T23:59:59Z",
  "startingPrice": 100
}

### Get active auctions
GET http://localhost:8080/api/auctions/active
