server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PW}

pricing-service:
  host: localhost
  port: 50051
