CREATE TABLE bids
(
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  auction_id UUID                                    NOT NULL,
  bidder_id  UUID                                    NOT NULL,
  amount     DECIMAL(10, 2)                          NOT NULL,
  timestamp  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
  CONSTRAINT pk_bids PRIMARY KEY (id)
);

CREATE INDEX idx_bids_auction_id ON bids (auction_id);
